ROOT_DIR = "cats"
TEST_ROOT_DIR="cat2"
ROOT_TARGET='target'
DEVICE = "cuda"

CHECKPOINT_DIR = "checkpoints/"
CHECKPOINT_GEN = "gen.pth.tar"
CHECKPOINT_DISC = "disc.pth.tar"

SHOW_MODEL = True

SAVE_MODEL = True
LOAD_MODEL = False

G_LEARNING_RATE = 0.1e-5
D_LEARNING_RATE = 0.1e-5

BATCH_SIZE = 1
IMAGE_SIZE = 64
CHANNELS_IMG = 3
DEPTH =4
NUM_EPOCHS = 200

SAVE_CHECKPOINT_FREQ = 10
SAVE_IMG_FREQ = 1

FEATURES_CRITIC = 64
FEATURES_GEN = 96

CRITIC_ITERATIONS = 1
Z_DIM = 4